### ISSUE TITLE
CMS migration

### ISSUE THREAD

**Issue by lucienlizlepiorz** [designcooperative/designcooperative.github.io#2]
@jdkunesh I am proposing that we use Kirby CMS. All work can be completed before purchase.

Personal $17 / Commercial $89: https://getkirby.com/buy

**Comment by lucienlizlepiorz** [comment]
@jdkunesh did some initial research. Looks like GitHub pages doesn't support server-side code(PHP, aka Kirby, Wordpress, etc.). Here's what I propose:

1. Can Kirby/CMS migration for now.
2. All blog content is Medium only.
3. Clean up HTML and CSS to allow for easy transition when the time comes.
4. Add links to site for Trello, Medium.

What do you think?

**Comment by jdkunesh** [comment]
Yeah, let's do this and use designcoop.co for the website and Medium for designcoop.blog.
If we want server-side include stuff we can use Jekyll.

**Comment by lucienlizlepiorz** [comment]
Transition/cleanup completed here: https://github.com/designcooperative/designcooperative.github.io/pull/7
